using System;
using System.Collections;
using Multiplayer;
using UnityEngine;

namespace TwilightCore;

/// <summary>
/// Runtime singleton that tracks the current collection run state and drives
/// level progression within a collection.
/// </summary>
public class CollectionManager : MonoBehaviour
{
    public static CollectionManager Instance { get; private set; }

    /// <summary>
    /// Whether the player is currently in the middle of a collection run.
    /// </summary>
    public bool IsInCollectionRun { get; private set; }

    /// <summary>
    /// Index of the current collection (into ConfigLoader.Collections).
    /// </summary>
    public int CurrentCollectionIndex { get; private set; }

    /// <summary>
    /// Index of the current level within the collection.
    /// </summary>
    public int CurrentLevelIndex { get; private set; }

    /// <summary>
    /// The CollectionDefinition being played.
    /// Returns the transient (random) collection when one is active,
    /// otherwise the config collection at CurrentCollectionIndex.
    /// </summary>
    public CollectionDefinition CurrentCollection
    {
        get
        {
            if (_transientCollection != null)
                return _transientCollection;
            var cols = ConfigLoader.Collections;
            if (CurrentCollectionIndex < 0 || CurrentCollectionIndex >= cols.Count)
                return null;
            return cols[CurrentCollectionIndex];
        }
    }

    /// <summary>
    /// The transient collection for the current run, if any. A transient
    /// collection (e.g. generated by "lc random") is NOT part of the config
    /// file — it only lives for the duration of its run. Null otherwise.
    /// </summary>
    private CollectionDefinition _transientCollection;

    /// <summary>
    /// True while the active run uses a transient collection (lc random)
    /// instead of one from the config file.
    /// </summary>
    public bool IsTransientRun => _transientCollection != null;

    /// <summary>
    /// The LevelId string of the current level.
    /// </summary>
    public string CurrentLevelId
    {
        get
        {
            var col = CurrentCollection;
            if (col == null || col.Levels == null || CurrentLevelIndex < 0 || CurrentLevelIndex >= col.Levels.Count)
                return null;
            return col.Levels[CurrentLevelIndex];
        }
    }

    /// <summary>
    /// True if the current level is the last one in the collection.
    /// </summary>
    public bool IsLastLevel
    {
        get
        {
            var col = CurrentCollection;
            return col != null && col.Levels != null && CurrentLevelIndex >= col.Levels.Count - 1;
        }
    }

    // ── Run lifecycle events (consumed by the timer / round reporter) ──────────
    //
    // Fired by the collection engine so an external module (the simulated timer
    // now, the real timer later) can react to level progression without coupling
    // to engine internals. All fire on the main thread (Unity frame).
    //
    /// <summary>A level started loading (levelId, levelIndex). Fires for the first level of a run too.</summary>
    public event Action<string, int> LevelStarted;

    /// <summary>The level/attempt at levelIndex just finished. skipped=true for lc skip / twi sim skip.</summary>
    public event Action<int, bool> LevelCompleted;

    /// <summary>The whole collection run finished normally (last level completed).</summary>
    public event Action RunCompleted;

    /// <summary>The run was aborted (player quit the level mid-run / exited the collection).</summary>
    public event Action RunAborted;

    private void Awake()
    {
        if (Instance != null)
        {
            Destroy(gameObject);
            return;
        }
        Instance = this;
        DontDestroyOnLoad(gameObject);
    }

    /// <summary>
    /// Begin a collection run starting from the given level index.
    /// </summary>
    public void StartCollectionRun(int collectionIndex, int startLevelIndex = 0)
    {
        // A new run supersedes any pending delayed console command and any
        // transient (lc random) run that was active.
        CancelDelayedCommand();
        _transientCollection = null;

        var cols = ConfigLoader.Collections;
        if (collectionIndex < 0 || collectionIndex >= cols.Count)
        {
            Plugin.Logger.LogError($"StartCollectionRun: invalid collection index {collectionIndex}");
            return;
        }

        var col = cols[collectionIndex];
        if (col.Levels == null || col.Levels.Count == 0)
        {
            Plugin.Logger.LogError($"StartCollectionRun: collection '{col.Name}' has no levels");
            return;
        }

        // Refuse to start if any level in the collection is invalid.
        foreach (var id in col.Levels)
        {
            bool isMissing;
            if (!ValidateLevelId(id, out isMissing))
            {
                Plugin.Logger.LogError(
                    $"StartCollectionRun: collection '{col.Name}' contains invalid level '{id}'. Aborting.");
                return;
            }
        }

        if (startLevelIndex < 0 || startLevelIndex >= col.Levels.Count)
            startLevelIndex = 0;

        CurrentCollectionIndex = collectionIndex;
        CurrentLevelIndex = startLevelIndex;
        IsInCollectionRun = true;

        var levelId = col.Levels[CurrentLevelIndex];
        Plugin.Logger.LogInfo($"Starting collection run: '{col.Name}' level {CurrentLevelIndex + 1}/{col.Levels.Count}: {levelId}");

        LaunchLevel(levelId);
    }

    /// <summary>
    /// Begin a run with a collection that is NOT in the config file
    /// (e.g. a random collection generated by "lc random"). The collection
    /// only exists for the duration of this run and is never persisted.
    /// CurrentCollectionIndex is set to -1 (no config entry); the transient
    /// collection is returned by CurrentCollection instead.
    /// Returns true if the run started (validation passed).
    /// </summary>
    public bool StartTransientCollectionRun(CollectionDefinition col)
    {
        if (col == null || col.Levels == null || col.Levels.Count == 0)
        {
            Plugin.Logger.LogError("StartTransientCollectionRun: collection has no levels");
            return false;
        }

        // Refuse to start if any level in the collection is invalid.
        foreach (var id in col.Levels)
        {
            bool isMissing;
            if (!ValidateLevelId(id, out isMissing))
            {
                Plugin.Logger.LogError(
                    $"StartTransientCollectionRun: collection '{col.Name}' contains invalid level '{id}'. Aborting.");
                return false;
            }
        }

        // A new run supersedes any pending delayed console command.
        CancelDelayedCommand();

        _transientCollection = col;
        CurrentCollectionIndex = -1;
        CurrentLevelIndex = 0;
        IsInCollectionRun = true;

        var levelId = col.Levels[0];
        Plugin.Logger.LogInfo(
            $"Starting random collection run: '{col.Name}' level 1/{col.Levels.Count}: {levelId}");

        LaunchLevel(levelId);
        return true;
    }

    /// <summary>
    /// Generate a random collection from the config's RandomLevelCount /
    /// RandomLevelPool and start a run with it (the "lc random" command).
    /// The generated collection is transient — never written to the config.
    /// Returns true on success; <paramref name="message"/> describes the
    /// result (drawn level list on success, an error description on failure).
    /// </summary>
    public bool GenerateAndStartRandomCollection(out string message)
    {
        var col = RandomCollectionGenerator.Generate(out message);
        if (col == null)
            return false;

        return StartTransientCollectionRun(col);
    }

    /// <summary>
    /// Advance to the next level in the collection, or end the run if this was the last.
    /// Called by the Harmony patch when a level is passed during a collection run.
    /// </summary>
    public void AdvanceToNextLevel(bool skipped = false)
    {
        if (!IsInCollectionRun)
            return;

        // The level/attempt at CurrentLevelIndex just finished (completed or skipped).
        // Fire before any state change so handlers see the index that completed.
        try { LevelCompleted?.Invoke(CurrentLevelIndex, skipped); }
        catch (Exception ex) { Plugin.Logger.LogWarning($"[CollectionManager] LevelCompleted handler threw: {ex}"); }

        if (IsLastLevel)
        {
            EndCollectionRun();
            return;
        }

        CurrentLevelIndex++;
        var col = CurrentCollection;
        var levelId = col.Levels[CurrentLevelIndex];
        Plugin.Logger.LogInfo($"Collection run advancing: '{col.Name}' level {CurrentLevelIndex + 1}/{col.Levels.Count}: {levelId}");

        LaunchLevel(levelId);
    }

    /// <summary>
    /// End the current collection run and return to the main menu.
    /// </summary>
    public void EndCollectionRun()
    {
        if (!IsInCollectionRun)
            return;

        var col = CurrentCollection;
        Plugin.Logger.LogInfo($"Collection run complete: '{col?.Name}'");
        IsInCollectionRun = false;
        _transientCollection = null;
        CancelDelayedCommand(); // a pending delayed command has nothing to act on anymore

        // Fire before PauseLeave so the reporter can flush project_complete before the scene tears down.
        try { RunCompleted?.Invoke(); }
        catch (Exception ex) { Plugin.Logger.LogWarning($"[CollectionManager] RunCompleted handler threw: {ex}"); }

        // Return to main menu
        if (App.instance != null)
        {
            App.instance.PauseLeave();
        }
    }

    /// <summary>
    /// Abort the collection run without finishing (e.g. player manually quits).
    /// </summary>
    public void AbortCollectionRun()
    {
        Plugin.Logger.LogInfo("Collection run aborted.");
        // Fire while the run is still "active" (handlers may inspect state).
        try { RunAborted?.Invoke(); }
        catch (Exception ex) { Plugin.Logger.LogWarning($"[CollectionManager] RunAborted handler threw: {ex}"); }
        IsInCollectionRun = false;
        _transientCollection = null;
        CancelDelayedCommand();
    }

    /// <summary>
    /// True while a delayed console command (lc restart/skip with a seconds
    /// argument) is waiting to fire.  New lc commands are refused meanwhile.
    /// </summary>
    public bool IsDelayedCommandPending => _pendingDelayedCommand != null;

    private Coroutine _pendingDelayedCommand;

    /// <summary>
    /// Schedule an action to run after <paramref name="delaySeconds"/>.
    /// The action is cancelled if the collection run ends (IsInCollectionRun
    /// becomes false) or the current collection changes before the delay
    /// elapses.  <paramref name="label"/> is used in the console countdown
    /// printed once per second during the final 5 seconds (e.g. "restart").
    /// Returns false (and logs) if another delayed command is already pending.
    /// </summary>
    public bool ScheduleAfterDelay(float delaySeconds, int expectedCollectionIndex, Action action, string label)
    {
        if (action == null)
            return false;
        if (_pendingDelayedCommand != null)
        {
            Plugin.Logger.LogWarning(
                "LevelCollections: a delayed command is already pending; refusing to schedule another.");
            return false;
        }
        _pendingDelayedCommand = StartCoroutine(DelayedAction(delaySeconds, expectedCollectionIndex, action, label));
        return true;
    }

    /// <summary>
    /// Cancel a pending delayed command (lc abort).  Returns true if there
    /// was a pending command that got cancelled.
    /// </summary>
    public bool CancelDelayedCommand()
    {
        if (_pendingDelayedCommand == null)
            return false;
        StopCoroutine(_pendingDelayedCommand);
        _pendingDelayedCommand = null;
        Plugin.Logger.LogInfo("LevelCollections: delayed command cancelled.");
        return true;
    }

    private IEnumerator DelayedAction(float delaySeconds, int expectedCollectionIndex, Action action, string label)
    {
        // Tick once per second; during the final 5 seconds print a countdown.
        float remaining = delaySeconds;
        while (remaining > 0f)
        {
            if (remaining <= 5f)
                Print($"lc: {(label ?? "command")} in {Mathf.CeilToInt(remaining)}s...");
            float step = Mathf.Min(1f, remaining);
            yield return new WaitForSeconds(step);
            remaining -= step;
        }

        // The timer has finished; clear the pending flag no matter what follows.
        _pendingDelayedCommand = null;

        if (!IsInCollectionRun || CurrentCollectionIndex != expectedCollectionIndex)
        {
            Plugin.Logger.LogInfo(
                "LevelCollections: delayed console command cancelled (collection run ended or changed).");
            yield break;
        }

        action();
    }

    /// <summary>
    /// Schedule an action that STARTS a new run (lc random) after
    /// <paramref name="delaySeconds"/>. Unlike <see cref="ScheduleAfterDelay"/>
    /// this does NOT require an active run: if no run is active when the
    /// command is scheduled, the action always fires (unless aborted). If a
    /// run IS active, the action is cancelled when that run ends or switches
    /// collection before the delay elapses. <paramref name="label"/> is used
    /// in the console countdown. Returns false (and logs) if another delayed
    /// command is already pending.
    /// </summary>
    public bool ScheduleStartAfterDelay(float delaySeconds, Action action, string label)
    {
        if (action == null)
            return false;
        if (_pendingDelayedCommand != null)
        {
            Plugin.Logger.LogWarning(
                "LevelCollections: a delayed command is already pending; refusing to schedule another.");
            return false;
        }
        bool wasRunning = IsInCollectionRun;
        int expectedCollectionIndex = CurrentCollectionIndex;
        _pendingDelayedCommand = StartCoroutine(
            DelayedStart(delaySeconds, wasRunning, expectedCollectionIndex, action, label));
        return true;
    }

    private IEnumerator DelayedStart(float delaySeconds, bool wasRunning, int expectedCollectionIndex, Action action, string label)
    {
        // Tick once per second; during the final 5 seconds print a countdown.
        float remaining = delaySeconds;
        while (remaining > 0f)
        {
            if (remaining <= 5f)
                Print($"lc: {(label ?? "command")} in {Mathf.CeilToInt(remaining)}s...");
            float step = Mathf.Min(1f, remaining);
            yield return new WaitForSeconds(step);
            remaining -= step;
        }

        // The timer has finished; clear the pending flag no matter what follows.
        _pendingDelayedCommand = null;

        // Cancel only if a run that was active when we started waiting has
        // ended or switched collection since.
        if (wasRunning && (!IsInCollectionRun || CurrentCollectionIndex != expectedCollectionIndex))
        {
            Plugin.Logger.LogInfo(
                "LevelCollections: delayed console command cancelled (collection run ended or changed).");
            yield break;
        }

        action();
    }

    /// <summary>
    /// Print to the game's dev console, falling back to the plugin logger if
    /// the Shell object isn't alive yet (Unity fake-null check).
    /// </summary>
    private static void Print(string message)
    {
        if (Shell.instance != null && Shell.instance)
            Shell.Print(message);
        else
            Plugin.Logger.LogInfo(message);
    }

    // ── Level type auto-detection ────────────────────────────────

    /// <summary>
    /// Validate a level ID string.  Returns true if the level ID is known
    /// and the corresponding content is available (subscribed, downloaded, etc.).
    ///
    /// When false is returned, <paramref name="isMissing"/> indicates whether
    /// the failure is because a workshop level is not subscribed (true) or
    /// because the ID is unrecognised/corrupt (false).  The UI uses this to
    /// choose the right error prefix: "(missing)" vs "(!)".
    /// </summary>
    public static bool ValidateLevelId(string levelId, out bool isMissing)
    {
        isMissing = false;
        if (string.IsNullOrEmpty(levelId))
            return false;

        var type = ResolveLevelType(levelId);

        // BuiltIn: must be in the known display-name dictionary.
        if (type == WorkshopItemSource.BuiltIn)
            return _builtInDisplayNameToIndex.ContainsKey(levelId);

        // EditorPick: must be listed in Game.instance.editorPickLevels.
        if (type == WorkshopItemSource.EditorPick)
        {
            if (Game.instance != null && Game.instance.editorPickLevels != null)
            {
                foreach (var name in Game.instance.editorPickLevels)
                    if (name == levelId) return true;
            }
            return false;
        }

        // Workshop (Subscription / LocalWorkshop): metadata must be available.
        var meta = ResolveWorkshopMetadata(levelId);
        if (meta == null)
        {
            if (type == WorkshopItemSource.Subscription)
                isMissing = true; // not subscribed
            return false;
        }
        return true;
    }

    /// <summary>
    /// Auto-detect the WorkshopItemSource from a LevelId string.
    /// </summary>
    public static WorkshopItemSource ResolveLevelType(string levelId)
    {
        if (string.IsNullOrEmpty(levelId))
            return WorkshopItemSource.BuiltIn;

        // BuiltIn: name in our dictionary
        if (_builtInDisplayNameToIndex.ContainsKey(levelId))
            return WorkshopItemSource.BuiltIn;

        // EditorPick: name in Game.instance.editorPickLevels[]
        if (Game.instance != null && Game.instance.editorPickLevels != null)
        {
            foreach (var name in Game.instance.editorPickLevels)
            {
                if (name == levelId)
                    return WorkshopItemSource.EditorPick;
            }
        }

        // LocalWorkshop: path-like string (contains "lvl:" prefix or path separators)
        if (levelId.StartsWith("lvl:") || levelId.Contains("/") || levelId.Contains("\\"))
            return WorkshopItemSource.LocalWorkshop;

        // Subscription: purely numeric workshop ID
        if (ulong.TryParse(levelId, out _))
            return WorkshopItemSource.Subscription;

        // Fallback
        return WorkshopItemSource.BuiltIn;
    }

    /// <summary>
    /// Look up WorkshopLevelMetadata for a level by its LevelId.
    /// Returns null for BuiltIn levels (use the dictionary instead).
    /// </summary>
    public static HumanAPI.WorkshopLevelMetadata ResolveWorkshopMetadata(string levelId)
    {
        var type = ResolveLevelType(levelId);
        if (type == WorkshopItemSource.BuiltIn)
            return null;

        var repo = WorkshopRepository.instance;
        if (repo == null)
            return null;

        var list = repo.levelRepo.BySource(type);
        if (list == null)
            return null;

        foreach (var meta in list)
        {
            switch (type)
            {
                case WorkshopItemSource.Subscription:
                    if (ulong.TryParse(levelId, out ulong wsId) && meta.workshopId == wsId)
                        return meta;
                    break;
                case WorkshopItemSource.EditorPick:
                    if (meta is HumanAPI.BuiltinLevelMetadata blm && blm.internalName == levelId)
                        return meta;
                    break;
                case WorkshopItemSource.LocalWorkshop:
                    if (meta.folder == levelId)
                        return meta;
                    break;
            }
        }

        return null;
    }

    /// <summary>
    /// Localized display name for a level in the CURRENT game language.
    ///
    /// BuiltIn and EditorPick names come from the game's own localisation
    /// table via the "LEVEL/&lt;id&gt;" term — exactly the lookup the game
    /// performs in WorkshopRepository.AddLevel() — so they follow the
    /// player's language and stay correct when the game adds new levels.
    /// Workshop levels (Subscription / LocalWorkshop) have no LEVEL/ term;
    /// they keep their author-provided metadata title, matching how the
    /// game's own level select shows them.
    ///
    /// Falls back to the raw LevelId when no localised name exists.
    /// </summary>
    public static string GetLocalizedLevelName(string levelId)
    {
        if (string.IsNullOrEmpty(levelId))
            return levelId;

        var type = ResolveLevelType(levelId);

        if (type == WorkshopItemSource.BuiltIn || type == WorkshopItemSource.EditorPick)
        {
            // Intro_Reprise has no LEVEL/ term in the localisation table;
            // the campaign shows it as "Reprise" in every language.
            if (levelId == "Intro_Reprise")
                return "Reprise";

            string localized;
            try
            {
                localized = I2.Loc.ScriptLocalization.Get("LEVEL/" + levelId);
            }
            catch (Exception ex)
            {
                Plugin.Logger.LogWarning(
                    $"[CollectionManager] localisation lookup failed for '{levelId}': {ex.Message}");
                localized = null;
            }
            // GetTermTranslation returns "Missing: <term>" for unknown terms.
            if (!string.IsNullOrEmpty(localized) && !localized.StartsWith("Missing:", StringComparison.Ordinal))
                return localized;

            // No LEVEL/ term (e.g. a newly added level the table does not
            // cover yet): fall back to the startup-time localised metadata
            // title (EditorPick only — BuiltIn resolves to null here).
            var metaFallback = ResolveWorkshopMetadata(levelId);
            if (metaFallback != null && !string.IsNullOrEmpty(metaFallback.title))
                return metaFallback.title;
            return levelId;
        }

        // Workshop (Subscription / LocalWorkshop): author-provided title.
        var meta = ResolveWorkshopMetadata(levelId);
        if (meta != null && !string.IsNullOrEmpty(meta.title))
            return meta.title;
        return levelId;
    }

    // ── Level launching ───────────────────────────────────────────

    private void LaunchLevel(string levelId)
    {
        // Notify subscribers (timer/reporter) that a fresh level/attempt is starting.
        try { LevelStarted?.Invoke(levelId, CurrentLevelIndex); }
        catch (Exception ex) { Plugin.Logger.LogWarning($"[CollectionManager] LevelStarted handler threw: {ex}"); }

        if (App.instance == null)
        {
            Plugin.Logger.LogError("App.instance is null, cannot launch level.");
            return;
        }

        var type = ResolveLevelType(levelId);

        switch (type)
        {
            case WorkshopItemSource.BuiltIn:
                ulong levelIndex = FindBuiltInLevelIndex(levelId);
                ResetCurrentLevelIfSame((int)levelIndex, levelId);
                App.instance.LaunchSinglePlayer(levelIndex, WorkshopItemSource.BuiltIn, 0, 0);
                break;

            case WorkshopItemSource.EditorPick:
                ulong epIndex = FindEditorPickLevelIndex(levelId);
                ResetCurrentLevelIfSame((int)epIndex, levelId);
                App.instance.LaunchSinglePlayer(epIndex, WorkshopItemSource.EditorPick, 0, 0);
                break;

            case WorkshopItemSource.LocalWorkshop:
                App.instance.LaunchCustomLevel(levelId, WorkshopItemSource.LocalWorkshop, 0, 0);
                break;

            case WorkshopItemSource.Subscription:
                if (ulong.TryParse(levelId, out ulong wsId))
                {
                    ResetCurrentLevelIfSame((int)wsId, levelId);
                    App.instance.LaunchSinglePlayer(wsId, WorkshopItemSource.Subscription, 0, 0);
                }
                else
                    Plugin.Logger.LogError($"Subscription level '{levelId}' is not a valid ulong.");
                break;

            default:
                Plugin.Logger.LogError($"Unsupported level type: {type}");
                break;
        }
    }

    /// <summary>
    /// If Game.instance.currentLevelNumber matches the target level index,
    /// reset it to -1 to force a full scene reload in Game.LoadLevel().
    /// The game normally skips scene reloading when currentLevelNumber equals
    /// the target (an optimisation that assumes the same level is never reloaded
    /// without going through the main menu first). Consecutive plays of the same
    /// level in a collection run break that assumption, so we force the reload.
    /// </summary>
    private static void ResetCurrentLevelIfSame(int targetIndex, string levelId)
    {
        if (Game.instance != null && Game.instance.currentLevelNumber == targetIndex)
        {
            Plugin.Logger.LogInfo(
                $"Same level reload detected (index {targetIndex}, \"{levelId}\"), " +
                "resetting currentLevelNumber to force scene reload.");
            Game.instance.currentLevelNumber = -1;
        }
    }

    // ── Index lookups ─────────────────────────────────────────────

    /// <summary>
    /// Maps Display Name (internalName from WorkshopRepository) →
    /// index into Game.instance.levels[] (scene names).
    /// Two base levels have divergent names: "Train"→scene "Push", "Water"→scene "River".
    /// "Intro_Reprise" (index 12) and "Credits" (index 13) are in levels[] but NOT
    /// registered in WorkshopRepository; their scene names and display names are identical.
    /// </summary>
    private static readonly System.Collections.Generic.Dictionary<string, int> _builtInDisplayNameToIndex = new System.Collections.Generic.Dictionary<string, int>
    {
        { "Intro",         0  },
        { "Train",         1  },  // scene: "Push"
        { "Carry",         2  },
        { "Climb",         3  },
        { "Break",         4  },
        { "Siege",         5  },
        { "Water",         6  },  // scene: "River"
        { "Power",         7  },
        { "Aztec",         8  },
        { "Halloween",     9  },
        { "Steam",         10 },
        { "Ice",           11 },
        { "Intro_Reprise", 12 },
        { "Credits",       13 },
    };

    private ulong FindBuiltInLevelIndex(string displayName)
    {
        if (_builtInDisplayNameToIndex.TryGetValue(displayName, out int idx))
            return (ulong)idx;

        Plugin.Logger.LogWarning($"Built-in level '{displayName}' not found in display name map; launching with index 0.");
        return 0;
    }

    private ulong FindEditorPickLevelIndex(string sceneName)
    {
        if (Game.instance != null && Game.instance.editorPickLevels != null)
        {
            for (int i = 0; i < Game.instance.editorPickLevels.Length; i++)
            {
                if (Game.instance.editorPickLevels[i] == sceneName)
                    return (ulong)i;
            }
        }
        return 0;
    }
}
